version: '3.8'
services:
  pucapp_users:
    build: .
    image: pucapp_users
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/users_db
    networks:
      - pucapp_infra_pucapp_network
networks:
  pucapp_infra_pucapp_network:
    external: true